/*
 * generated by Xtext 2.12.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.services.SynthesizerGrammarAccess;
import org.xtext.synthesizer.Button;
import org.xtext.synthesizer.Model;
import org.xtext.synthesizer.SynthesizerPackage;

@SuppressWarnings("all")
public class SynthesizerSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SynthesizerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SynthesizerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SynthesizerPackage.BUTTON:
				sequence_Button(context, (Button) semanticObject); 
				return; 
			case SynthesizerPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ControlElement returns Button
	 *     Button returns Button
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         x=INT 
	 *         y=INT 
	 *         width=INT 
	 *         height=INT 
	 *         frequency=INT
	 *     )
	 */
	protected void sequence_Button(ISerializationContext context, Button semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__NAME));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__X));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__Y));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__WIDTH));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__HEIGHT));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__FREQUENCY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__FREQUENCY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getButtonAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getButtonAccess().getXINTTerminalRuleCall_4_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getButtonAccess().getYINTTerminalRuleCall_6_0(), semanticObject.getY());
		feeder.accept(grammarAccess.getButtonAccess().getWidthINTTerminalRuleCall_8_0(), semanticObject.getWidth());
		feeder.accept(grammarAccess.getButtonAccess().getHeightINTTerminalRuleCall_10_0(), semanticObject.getHeight());
		feeder.accept(grammarAccess.getButtonAccess().getFrequencyINTTerminalRuleCall_12_0(), semanticObject.getFrequency());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     controls+=ControlElement+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
