/*
 * generated by Xtext 2.12.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.services.SynthesizerGrammarAccess;
import org.xtext.synthesizer.Button;
import org.xtext.synthesizer.ConnectionElement;
import org.xtext.synthesizer.Model;
import org.xtext.synthesizer.RotaryKnob;
import org.xtext.synthesizer.SawToothOscillator;
import org.xtext.synthesizer.SineOscillator;
import org.xtext.synthesizer.Slider;
import org.xtext.synthesizer.SynthesizerPackage;

@SuppressWarnings("all")
public class SynthesizerSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SynthesizerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SynthesizerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SynthesizerPackage.BUTTON:
				sequence_Button(context, (Button) semanticObject); 
				return; 
			case SynthesizerPackage.CONNECTION_ELEMENT:
				sequence_ConnectionElement(context, (ConnectionElement) semanticObject); 
				return; 
			case SynthesizerPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case SynthesizerPackage.ROTARY_KNOB:
				sequence_RotaryKnob(context, (RotaryKnob) semanticObject); 
				return; 
			case SynthesizerPackage.SAW_TOOTH_OSCILLATOR:
				sequence_SawToothOscillator(context, (SawToothOscillator) semanticObject); 
				return; 
			case SynthesizerPackage.SINE_OSCILLATOR:
				sequence_SineOscillator(context, (SineOscillator) semanticObject); 
				return; 
			case SynthesizerPackage.SLIDER:
				sequence_Slider(context, (Slider) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ControlElement returns Button
	 *     Button returns Button
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         x=INT 
	 *         y=INT 
	 *         width=INT 
	 *         height=INT 
	 *         sound=[SoundElement|ID]
	 *     )
	 */
	protected void sequence_Button(ISerializationContext context, Button semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__X));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__Y));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__WIDTH));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__HEIGHT));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.BUTTON__SOUND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.BUTTON__SOUND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getButtonAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getButtonAccess().getXINTTerminalRuleCall_4_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getButtonAccess().getYINTTerminalRuleCall_6_0(), semanticObject.getY());
		feeder.accept(grammarAccess.getButtonAccess().getWidthINTTerminalRuleCall_8_0(), semanticObject.getWidth());
		feeder.accept(grammarAccess.getButtonAccess().getHeightINTTerminalRuleCall_10_0(), semanticObject.getHeight());
		feeder.accept(grammarAccess.getButtonAccess().getSoundSoundElementIDTerminalRuleCall_12_0_1(), semanticObject.eGet(SynthesizerPackage.Literals.BUTTON__SOUND, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ConnectionElement returns ConnectionElement
	 *
	 * Constraint:
	 *     (ce=[ControlElement|ID] se=[SoundElement|ID])
	 */
	protected void sequence_ConnectionElement(ISerializationContext context, ConnectionElement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONNECTION_ELEMENT__CE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONNECTION_ELEMENT__CE));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONNECTION_ELEMENT__SE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONNECTION_ELEMENT__SE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConnectionElementAccess().getCeControlElementIDTerminalRuleCall_1_0_1(), semanticObject.eGet(SynthesizerPackage.Literals.CONNECTION_ELEMENT__CE, false));
		feeder.accept(grammarAccess.getConnectionElementAccess().getSeSoundElementIDTerminalRuleCall_2_0_1(), semanticObject.eGet(SynthesizerPackage.Literals.CONNECTION_ELEMENT__SE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (controls+=ControlElement* sounds+=SoundElement* connections+=ConnectionElement*)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ControlElement returns RotaryKnob
	 *     RotaryKnob returns RotaryKnob
	 *
	 * Constraint:
	 *     (name=ID x=INT y=INT width=INT height=INT)
	 */
	protected void sequence_RotaryKnob(ISerializationContext context, RotaryKnob semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__X));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__Y));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__WIDTH));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__HEIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRotaryKnobAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRotaryKnobAccess().getXINTTerminalRuleCall_4_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getRotaryKnobAccess().getYINTTerminalRuleCall_6_0(), semanticObject.getY());
		feeder.accept(grammarAccess.getRotaryKnobAccess().getWidthINTTerminalRuleCall_8_0(), semanticObject.getWidth());
		feeder.accept(grammarAccess.getRotaryKnobAccess().getHeightINTTerminalRuleCall_10_0(), semanticObject.getHeight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SoundElement returns SawToothOscillator
	 *     SawToothOscillator returns SawToothOscillator
	 *
	 * Constraint:
	 *     (name=ID frequency=INT amplitude=INT)
	 */
	protected void sequence_SawToothOscillator(ISerializationContext context, SawToothOscillator semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__FREQUENCY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__FREQUENCY));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__AMPLITUDE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__AMPLITUDE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSawToothOscillatorAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSawToothOscillatorAccess().getFrequencyINTTerminalRuleCall_4_0(), semanticObject.getFrequency());
		feeder.accept(grammarAccess.getSawToothOscillatorAccess().getAmplitudeINTTerminalRuleCall_6_0(), semanticObject.getAmplitude());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SoundElement returns SineOscillator
	 *     SineOscillator returns SineOscillator
	 *
	 * Constraint:
	 *     (name=ID frequency=INT amplitude=INT)
	 */
	protected void sequence_SineOscillator(ISerializationContext context, SineOscillator semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__FREQUENCY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__FREQUENCY));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__AMPLITUDE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.SOUND_ELEMENT__AMPLITUDE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSineOscillatorAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSineOscillatorAccess().getFrequencyINTTerminalRuleCall_4_0(), semanticObject.getFrequency());
		feeder.accept(grammarAccess.getSineOscillatorAccess().getAmplitudeINTTerminalRuleCall_6_0(), semanticObject.getAmplitude());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ControlElement returns Slider
	 *     Slider returns Slider
	 *
	 * Constraint:
	 *     (name=ID x=INT y=INT width=INT height=INT)
	 */
	protected void sequence_Slider(ISerializationContext context, Slider semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__X));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__Y));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__WIDTH));
			if (transientValues.isValueTransient(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SynthesizerPackage.Literals.CONTROL_ELEMENT__HEIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSliderAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSliderAccess().getXINTTerminalRuleCall_4_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getSliderAccess().getYINTTerminalRuleCall_6_0(), semanticObject.getY());
		feeder.accept(grammarAccess.getSliderAccess().getWidthINTTerminalRuleCall_8_0(), semanticObject.getWidth());
		feeder.accept(grammarAccess.getSliderAccess().getHeightINTTerminalRuleCall_10_0(), semanticObject.getHeight());
		feeder.finish();
	}
	
	
}
