/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.synthesizer.PulseOscillator;
import org.xtext.synthesizer.SynthesizerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pulse Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PulseOscillatorImpl extends SoundElementImpl implements PulseOscillator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PulseOscillatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SynthesizerPackage.Literals.PULSE_OSCILLATOR;
  }

} //PulseOscillatorImpl
