/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.synthesizer.RotaryKnob;
import org.xtext.synthesizer.SynthesizerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rotary Knob</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RotaryKnobImpl extends ControlElementImpl implements RotaryKnob
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RotaryKnobImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SynthesizerPackage.Literals.ROTARY_KNOB;
  }

} //RotaryKnobImpl
