/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.synthesizer.SawToothOscillator;
import org.xtext.synthesizer.SynthesizerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Saw Tooth Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SawToothOscillatorImpl extends SoundElementImpl implements SawToothOscillator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SawToothOscillatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SynthesizerPackage.Literals.SAW_TOOTH_OSCILLATOR;
  }

} //SawToothOscillatorImpl
