/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.synthesizer.SineOscillator;
import org.xtext.synthesizer.SynthesizerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sine Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SineOscillatorImpl extends SoundElementImpl implements SineOscillator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SineOscillatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SynthesizerPackage.Literals.SINE_OSCILLATOR;
  }

} //SineOscillatorImpl
