/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.synthesizer.SineOscillator;
import org.xtext.synthesizer.SynthesizerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sine Oscillator</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.synthesizer.impl.SineOscillatorImpl#getFrequency <em>Frequency</em>}</li>
 *   <li>{@link org.xtext.synthesizer.impl.SineOscillatorImpl#getAmplitude <em>Amplitude</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SineOscillatorImpl extends SoundElementImpl implements SineOscillator
{
  /**
   * The default value of the '{@link #getFrequency() <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrequency()
   * @generated
   * @ordered
   */
  protected static final int FREQUENCY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFrequency() <em>Frequency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrequency()
   * @generated
   * @ordered
   */
  protected int frequency = FREQUENCY_EDEFAULT;

  /**
   * The default value of the '{@link #getAmplitude() <em>Amplitude</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmplitude()
   * @generated
   * @ordered
   */
  protected static final int AMPLITUDE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAmplitude() <em>Amplitude</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmplitude()
   * @generated
   * @ordered
   */
  protected int amplitude = AMPLITUDE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SineOscillatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SynthesizerPackage.Literals.SINE_OSCILLATOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getFrequency()
  {
    return frequency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFrequency(int newFrequency)
  {
    int oldFrequency = frequency;
    frequency = newFrequency;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SynthesizerPackage.SINE_OSCILLATOR__FREQUENCY, oldFrequency, frequency));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getAmplitude()
  {
    return amplitude;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAmplitude(int newAmplitude)
  {
    int oldAmplitude = amplitude;
    amplitude = newAmplitude;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SynthesizerPackage.SINE_OSCILLATOR__AMPLITUDE, oldAmplitude, amplitude));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SynthesizerPackage.SINE_OSCILLATOR__FREQUENCY:
        return getFrequency();
      case SynthesizerPackage.SINE_OSCILLATOR__AMPLITUDE:
        return getAmplitude();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SynthesizerPackage.SINE_OSCILLATOR__FREQUENCY:
        setFrequency((Integer)newValue);
        return;
      case SynthesizerPackage.SINE_OSCILLATOR__AMPLITUDE:
        setAmplitude((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SynthesizerPackage.SINE_OSCILLATOR__FREQUENCY:
        setFrequency(FREQUENCY_EDEFAULT);
        return;
      case SynthesizerPackage.SINE_OSCILLATOR__AMPLITUDE:
        setAmplitude(AMPLITUDE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SynthesizerPackage.SINE_OSCILLATOR__FREQUENCY:
        return frequency != FREQUENCY_EDEFAULT;
      case SynthesizerPackage.SINE_OSCILLATOR__AMPLITUDE:
        return amplitude != AMPLITUDE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (frequency: ");
    result.append(frequency);
    result.append(", amplitude: ");
    result.append(amplitude);
    result.append(')');
    return result.toString();
  }

} //SineOscillatorImpl
