/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.synthesizer.SynthesizerPackage;
import org.xtext.synthesizer.TriangleOscillator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Triangle Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TriangleOscillatorImpl extends SoundElementImpl implements TriangleOscillator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TriangleOscillatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SynthesizerPackage.Literals.TRIANGLE_OSCILLATOR;
  }

} //TriangleOscillatorImpl
