/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connection Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.synthesizer.ConnectionElement#getCe <em>Ce</em>}</li>
 *   <li>{@link org.xtext.synthesizer.ConnectionElement#getSe <em>Se</em>}</li>
 * </ul>
 *
 * @see org.xtext.synthesizer.SynthesizerPackage#getConnectionElement()
 * @model
 * @generated
 */
public interface ConnectionElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Ce</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ce</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ce</em>' reference.
   * @see #setCe(ControlElement)
   * @see org.xtext.synthesizer.SynthesizerPackage#getConnectionElement_Ce()
   * @model
   * @generated
   */
  ControlElement getCe();

  /**
   * Sets the value of the '{@link org.xtext.synthesizer.ConnectionElement#getCe <em>Ce</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ce</em>' reference.
   * @see #getCe()
   * @generated
   */
  void setCe(ControlElement value);

  /**
   * Returns the value of the '<em><b>Se</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Se</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Se</em>' reference.
   * @see #setSe(SoundElement)
   * @see org.xtext.synthesizer.SynthesizerPackage#getConnectionElement_Se()
   * @model
   * @generated
   */
  SoundElement getSe();

  /**
   * Sets the value of the '{@link org.xtext.synthesizer.ConnectionElement#getSe <em>Se</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Se</em>' reference.
   * @see #getSe()
   * @generated
   */
  void setSe(SoundElement value);

} // ConnectionElement
