/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.synthesizer.SynthesizerPackage#getControlElement()
 * @model
 * @generated
 */
public interface ControlElement extends EObject
{
} // ControlElement
