/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pulse Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.synthesizer.SynthesizerPackage#getPulseOscillator()
 * @model
 * @generated
 */
public interface PulseOscillator extends SoundElement
{
} // PulseOscillator
