/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotary Knob</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.synthesizer.SynthesizerPackage#getRotaryKnob()
 * @model
 * @generated
 */
public interface RotaryKnob extends ControlElement
{
} // RotaryKnob
