/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Saw Tooth Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.synthesizer.SynthesizerPackage#getSawToothOscillator()
 * @model
 * @generated
 */
public interface SawToothOscillator extends SoundElement
{
} // SawToothOscillator
