/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Saw Tooth Oscillator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.synthesizer.SawToothOscillator#getMin <em>Min</em>}</li>
 *   <li>{@link org.xtext.synthesizer.SawToothOscillator#getMax <em>Max</em>}</li>
 *   <li>{@link org.xtext.synthesizer.SawToothOscillator#getDefault <em>Default</em>}</li>
 * </ul>
 *
 * @see org.xtext.synthesizer.SynthesizerPackage#getSawToothOscillator()
 * @model
 * @generated
 */
public interface SawToothOscillator extends SoundElement
{
  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute.
   * @see #setMin(int)
   * @see org.xtext.synthesizer.SynthesizerPackage#getSawToothOscillator_Min()
   * @model
   * @generated
   */
  int getMin();

  /**
   * Sets the value of the '{@link org.xtext.synthesizer.SawToothOscillator#getMin <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min</em>' attribute.
   * @see #getMin()
   * @generated
   */
  void setMin(int value);

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see org.xtext.synthesizer.SynthesizerPackage#getSawToothOscillator_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link org.xtext.synthesizer.SawToothOscillator#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Default</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(int)
   * @see org.xtext.synthesizer.SynthesizerPackage#getSawToothOscillator_Default()
   * @model
   * @generated
   */
  int getDefault();

  /**
   * Sets the value of the '{@link org.xtext.synthesizer.SawToothOscillator#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(int value);

} // SawToothOscillator
