/**
 * generated by Xtext 2.12.0
 */
package org.xtext.synthesizer;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.synthesizer.SynthesizerFactory
 * @model kind="package"
 * @generated
 */
public interface SynthesizerPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "synthesizer";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/Synthesizer";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "synthesizer";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SynthesizerPackage eINSTANCE = org.xtext.synthesizer.impl.SynthesizerPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.ModelImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Controls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONTROLS = 0;

  /**
   * The feature id for the '<em><b>Sounds</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SOUNDS = 1;

  /**
   * The feature id for the '<em><b>Connections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONNECTIONS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.ControlElementImpl <em>Control Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.ControlElementImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getControlElement()
   * @generated
   */
  int CONTROL_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_ELEMENT__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_ELEMENT__Y = 2;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_ELEMENT__WIDTH = 3;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_ELEMENT__HEIGHT = 4;

  /**
   * The number of structural features of the '<em>Control Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_ELEMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.RotaryKnobImpl <em>Rotary Knob</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.RotaryKnobImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getRotaryKnob()
   * @generated
   */
  int ROTARY_KNOB = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTARY_KNOB__NAME = CONTROL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTARY_KNOB__X = CONTROL_ELEMENT__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTARY_KNOB__Y = CONTROL_ELEMENT__Y;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTARY_KNOB__WIDTH = CONTROL_ELEMENT__WIDTH;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTARY_KNOB__HEIGHT = CONTROL_ELEMENT__HEIGHT;

  /**
   * The number of structural features of the '<em>Rotary Knob</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTARY_KNOB_FEATURE_COUNT = CONTROL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.SliderImpl <em>Slider</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.SliderImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSlider()
   * @generated
   */
  int SLIDER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__NAME = CONTROL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__X = CONTROL_ELEMENT__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__Y = CONTROL_ELEMENT__Y;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__WIDTH = CONTROL_ELEMENT__WIDTH;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__HEIGHT = CONTROL_ELEMENT__HEIGHT;

  /**
   * The feature id for the '<em><b>Sound</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__SOUND = CONTROL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER__TYPE = CONTROL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Slider</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLIDER_FEATURE_COUNT = CONTROL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.SoundElementImpl <em>Sound Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.SoundElementImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSoundElement()
   * @generated
   */
  int SOUND_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND_ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND_ELEMENT__FREQUENCY = 1;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND_ELEMENT__AMPLITUDE = 2;

  /**
   * The number of structural features of the '<em>Sound Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND_ELEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.ButtonImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = CONTROL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__X = CONTROL_ELEMENT__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__Y = CONTROL_ELEMENT__Y;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__WIDTH = CONTROL_ELEMENT__WIDTH;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__HEIGHT = CONTROL_ELEMENT__HEIGHT;

  /**
   * The feature id for the '<em><b>Sound</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__SOUND = CONTROL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = CONTROL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.ConnectionElementImpl <em>Connection Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.ConnectionElementImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getConnectionElement()
   * @generated
   */
  int CONNECTION_ELEMENT = 6;

  /**
   * The feature id for the '<em><b>Ce</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_ELEMENT__CE = 0;

  /**
   * The feature id for the '<em><b>Se</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_ELEMENT__SE = 1;

  /**
   * The number of structural features of the '<em>Connection Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.SawToothOscillatorImpl <em>Saw Tooth Oscillator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.SawToothOscillatorImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSawToothOscillator()
   * @generated
   */
  int SAW_TOOTH_OSCILLATOR = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAW_TOOTH_OSCILLATOR__NAME = SOUND_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAW_TOOTH_OSCILLATOR__FREQUENCY = SOUND_ELEMENT__FREQUENCY;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAW_TOOTH_OSCILLATOR__AMPLITUDE = SOUND_ELEMENT__AMPLITUDE;

  /**
   * The number of structural features of the '<em>Saw Tooth Oscillator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAW_TOOTH_OSCILLATOR_FEATURE_COUNT = SOUND_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.SineOscillatorImpl <em>Sine Oscillator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.SineOscillatorImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSineOscillator()
   * @generated
   */
  int SINE_OSCILLATOR = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINE_OSCILLATOR__NAME = SOUND_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINE_OSCILLATOR__FREQUENCY = SOUND_ELEMENT__FREQUENCY;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINE_OSCILLATOR__AMPLITUDE = SOUND_ELEMENT__AMPLITUDE;

  /**
   * The number of structural features of the '<em>Sine Oscillator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINE_OSCILLATOR_FEATURE_COUNT = SOUND_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.TriangleOscillatorImpl <em>Triangle Oscillator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.TriangleOscillatorImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getTriangleOscillator()
   * @generated
   */
  int TRIANGLE_OSCILLATOR = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIANGLE_OSCILLATOR__NAME = SOUND_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIANGLE_OSCILLATOR__FREQUENCY = SOUND_ELEMENT__FREQUENCY;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIANGLE_OSCILLATOR__AMPLITUDE = SOUND_ELEMENT__AMPLITUDE;

  /**
   * The number of structural features of the '<em>Triangle Oscillator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIANGLE_OSCILLATOR_FEATURE_COUNT = SOUND_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.SquareOscillatorImpl <em>Square Oscillator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.SquareOscillatorImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSquareOscillator()
   * @generated
   */
  int SQUARE_OSCILLATOR = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUARE_OSCILLATOR__NAME = SOUND_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUARE_OSCILLATOR__FREQUENCY = SOUND_ELEMENT__FREQUENCY;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUARE_OSCILLATOR__AMPLITUDE = SOUND_ELEMENT__AMPLITUDE;

  /**
   * The number of structural features of the '<em>Square Oscillator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUARE_OSCILLATOR_FEATURE_COUNT = SOUND_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.PulseOscillatorImpl <em>Pulse Oscillator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.PulseOscillatorImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getPulseOscillator()
   * @generated
   */
  int PULSE_OSCILLATOR = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PULSE_OSCILLATOR__NAME = SOUND_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PULSE_OSCILLATOR__FREQUENCY = SOUND_ELEMENT__FREQUENCY;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PULSE_OSCILLATOR__AMPLITUDE = SOUND_ELEMENT__AMPLITUDE;

  /**
   * The number of structural features of the '<em>Pulse Oscillator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PULSE_OSCILLATOR_FEATURE_COUNT = SOUND_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.synthesizer.impl.ImpulseOscillatorImpl <em>Impulse Oscillator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.synthesizer.impl.ImpulseOscillatorImpl
   * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getImpulseOscillator()
   * @generated
   */
  int IMPULSE_OSCILLATOR = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPULSE_OSCILLATOR__NAME = SOUND_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPULSE_OSCILLATOR__FREQUENCY = SOUND_ELEMENT__FREQUENCY;

  /**
   * The feature id for the '<em><b>Amplitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPULSE_OSCILLATOR__AMPLITUDE = SOUND_ELEMENT__AMPLITUDE;

  /**
   * The number of structural features of the '<em>Impulse Oscillator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPULSE_OSCILLATOR_FEATURE_COUNT = SOUND_ELEMENT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.synthesizer.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.synthesizer.Model#getControls <em>Controls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Controls</em>'.
   * @see org.xtext.synthesizer.Model#getControls()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Controls();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.synthesizer.Model#getSounds <em>Sounds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sounds</em>'.
   * @see org.xtext.synthesizer.Model#getSounds()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Sounds();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.synthesizer.Model#getConnections <em>Connections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Connections</em>'.
   * @see org.xtext.synthesizer.Model#getConnections()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Connections();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.ControlElement <em>Control Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Control Element</em>'.
   * @see org.xtext.synthesizer.ControlElement
   * @generated
   */
  EClass getControlElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.ControlElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.synthesizer.ControlElement#getName()
   * @see #getControlElement()
   * @generated
   */
  EAttribute getControlElement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.ControlElement#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.synthesizer.ControlElement#getX()
   * @see #getControlElement()
   * @generated
   */
  EAttribute getControlElement_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.ControlElement#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.synthesizer.ControlElement#getY()
   * @see #getControlElement()
   * @generated
   */
  EAttribute getControlElement_Y();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.ControlElement#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.xtext.synthesizer.ControlElement#getWidth()
   * @see #getControlElement()
   * @generated
   */
  EAttribute getControlElement_Width();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.ControlElement#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.synthesizer.ControlElement#getHeight()
   * @see #getControlElement()
   * @generated
   */
  EAttribute getControlElement_Height();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.RotaryKnob <em>Rotary Knob</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotary Knob</em>'.
   * @see org.xtext.synthesizer.RotaryKnob
   * @generated
   */
  EClass getRotaryKnob();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.Slider <em>Slider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Slider</em>'.
   * @see org.xtext.synthesizer.Slider
   * @generated
   */
  EClass getSlider();

  /**
   * Returns the meta object for the reference '{@link org.xtext.synthesizer.Slider#getSound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sound</em>'.
   * @see org.xtext.synthesizer.Slider#getSound()
   * @see #getSlider()
   * @generated
   */
  EReference getSlider_Sound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.Slider#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.synthesizer.Slider#getType()
   * @see #getSlider()
   * @generated
   */
  EAttribute getSlider_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.SoundElement <em>Sound Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sound Element</em>'.
   * @see org.xtext.synthesizer.SoundElement
   * @generated
   */
  EClass getSoundElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.SoundElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.synthesizer.SoundElement#getName()
   * @see #getSoundElement()
   * @generated
   */
  EAttribute getSoundElement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.SoundElement#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frequency</em>'.
   * @see org.xtext.synthesizer.SoundElement#getFrequency()
   * @see #getSoundElement()
   * @generated
   */
  EAttribute getSoundElement_Frequency();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.synthesizer.SoundElement#getAmplitude <em>Amplitude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amplitude</em>'.
   * @see org.xtext.synthesizer.SoundElement#getAmplitude()
   * @see #getSoundElement()
   * @generated
   */
  EAttribute getSoundElement_Amplitude();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.synthesizer.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the reference '{@link org.xtext.synthesizer.Button#getSound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sound</em>'.
   * @see org.xtext.synthesizer.Button#getSound()
   * @see #getButton()
   * @generated
   */
  EReference getButton_Sound();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.ConnectionElement <em>Connection Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection Element</em>'.
   * @see org.xtext.synthesizer.ConnectionElement
   * @generated
   */
  EClass getConnectionElement();

  /**
   * Returns the meta object for the reference '{@link org.xtext.synthesizer.ConnectionElement#getCe <em>Ce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ce</em>'.
   * @see org.xtext.synthesizer.ConnectionElement#getCe()
   * @see #getConnectionElement()
   * @generated
   */
  EReference getConnectionElement_Ce();

  /**
   * Returns the meta object for the reference '{@link org.xtext.synthesizer.ConnectionElement#getSe <em>Se</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Se</em>'.
   * @see org.xtext.synthesizer.ConnectionElement#getSe()
   * @see #getConnectionElement()
   * @generated
   */
  EReference getConnectionElement_Se();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.SawToothOscillator <em>Saw Tooth Oscillator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Saw Tooth Oscillator</em>'.
   * @see org.xtext.synthesizer.SawToothOscillator
   * @generated
   */
  EClass getSawToothOscillator();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.SineOscillator <em>Sine Oscillator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sine Oscillator</em>'.
   * @see org.xtext.synthesizer.SineOscillator
   * @generated
   */
  EClass getSineOscillator();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.TriangleOscillator <em>Triangle Oscillator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Triangle Oscillator</em>'.
   * @see org.xtext.synthesizer.TriangleOscillator
   * @generated
   */
  EClass getTriangleOscillator();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.SquareOscillator <em>Square Oscillator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Square Oscillator</em>'.
   * @see org.xtext.synthesizer.SquareOscillator
   * @generated
   */
  EClass getSquareOscillator();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.PulseOscillator <em>Pulse Oscillator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pulse Oscillator</em>'.
   * @see org.xtext.synthesizer.PulseOscillator
   * @generated
   */
  EClass getPulseOscillator();

  /**
   * Returns the meta object for class '{@link org.xtext.synthesizer.ImpulseOscillator <em>Impulse Oscillator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Impulse Oscillator</em>'.
   * @see org.xtext.synthesizer.ImpulseOscillator
   * @generated
   */
  EClass getImpulseOscillator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SynthesizerFactory getSynthesizerFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.ModelImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Controls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONTROLS = eINSTANCE.getModel_Controls();

    /**
     * The meta object literal for the '<em><b>Sounds</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SOUNDS = eINSTANCE.getModel_Sounds();

    /**
     * The meta object literal for the '<em><b>Connections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONNECTIONS = eINSTANCE.getModel_Connections();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.ControlElementImpl <em>Control Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.ControlElementImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getControlElement()
     * @generated
     */
    EClass CONTROL_ELEMENT = eINSTANCE.getControlElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL_ELEMENT__NAME = eINSTANCE.getControlElement_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL_ELEMENT__X = eINSTANCE.getControlElement_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL_ELEMENT__Y = eINSTANCE.getControlElement_Y();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL_ELEMENT__WIDTH = eINSTANCE.getControlElement_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL_ELEMENT__HEIGHT = eINSTANCE.getControlElement_Height();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.RotaryKnobImpl <em>Rotary Knob</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.RotaryKnobImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getRotaryKnob()
     * @generated
     */
    EClass ROTARY_KNOB = eINSTANCE.getRotaryKnob();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.SliderImpl <em>Slider</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.SliderImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSlider()
     * @generated
     */
    EClass SLIDER = eINSTANCE.getSlider();

    /**
     * The meta object literal for the '<em><b>Sound</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SLIDER__SOUND = eINSTANCE.getSlider_Sound();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLIDER__TYPE = eINSTANCE.getSlider_Type();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.SoundElementImpl <em>Sound Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.SoundElementImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSoundElement()
     * @generated
     */
    EClass SOUND_ELEMENT = eINSTANCE.getSoundElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOUND_ELEMENT__NAME = eINSTANCE.getSoundElement_Name();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOUND_ELEMENT__FREQUENCY = eINSTANCE.getSoundElement_Frequency();

    /**
     * The meta object literal for the '<em><b>Amplitude</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOUND_ELEMENT__AMPLITUDE = eINSTANCE.getSoundElement_Amplitude();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.ButtonImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Sound</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__SOUND = eINSTANCE.getButton_Sound();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.ConnectionElementImpl <em>Connection Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.ConnectionElementImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getConnectionElement()
     * @generated
     */
    EClass CONNECTION_ELEMENT = eINSTANCE.getConnectionElement();

    /**
     * The meta object literal for the '<em><b>Ce</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION_ELEMENT__CE = eINSTANCE.getConnectionElement_Ce();

    /**
     * The meta object literal for the '<em><b>Se</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION_ELEMENT__SE = eINSTANCE.getConnectionElement_Se();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.SawToothOscillatorImpl <em>Saw Tooth Oscillator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.SawToothOscillatorImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSawToothOscillator()
     * @generated
     */
    EClass SAW_TOOTH_OSCILLATOR = eINSTANCE.getSawToothOscillator();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.SineOscillatorImpl <em>Sine Oscillator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.SineOscillatorImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSineOscillator()
     * @generated
     */
    EClass SINE_OSCILLATOR = eINSTANCE.getSineOscillator();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.TriangleOscillatorImpl <em>Triangle Oscillator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.TriangleOscillatorImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getTriangleOscillator()
     * @generated
     */
    EClass TRIANGLE_OSCILLATOR = eINSTANCE.getTriangleOscillator();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.SquareOscillatorImpl <em>Square Oscillator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.SquareOscillatorImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getSquareOscillator()
     * @generated
     */
    EClass SQUARE_OSCILLATOR = eINSTANCE.getSquareOscillator();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.PulseOscillatorImpl <em>Pulse Oscillator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.PulseOscillatorImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getPulseOscillator()
     * @generated
     */
    EClass PULSE_OSCILLATOR = eINSTANCE.getPulseOscillator();

    /**
     * The meta object literal for the '{@link org.xtext.synthesizer.impl.ImpulseOscillatorImpl <em>Impulse Oscillator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.synthesizer.impl.ImpulseOscillatorImpl
     * @see org.xtext.synthesizer.impl.SynthesizerPackageImpl#getImpulseOscillator()
     * @generated
     */
    EClass IMPULSE_OSCILLATOR = eINSTANCE.getImpulseOscillator();

  }

} //SynthesizerPackage
