/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.SynthesizerStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SynthesizerStandaloneSetup extends SynthesizerStandaloneSetupGenerated {
  public static void doSetup() {
    new SynthesizerStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
