/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.ui.internal.XtextActivator;

public class SynthesizerUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.xtext.Synthesizer");
	}

}
